DROP TABLE TouristicSite;
DROP TABLE Hotel;
DROP TABLE Location;
DROP TABLE Description;

CREATE TABLE Location(
  ID_L INTEGER AUTO_INCREMENT,
  X INTEGER Not NULL,
  Y INTEGER NOT NULL,
  PRIMARY  KEY(ID_L)
);


CREATE TABLE TouristicSite
(
    S_ID     INTEGER NOT NULL AUTO_INCREMENT,
    S_NAME   VARCHAR(100) NOT NULL,
    TYPE     ENUM('historic', 'activity'),
    ID_L INTEGER,
    FOREIGN KEY (ID_L) REFERENCES Location(ID_L) ON DELETE CASCADE,
    PRIMARY KEY(S_ID,S_NAME)
  );

CREATE TABLE Hotel
  (
    H_ID  INTEGER NOT NULL AUTO_INCREMENT,
    H_NAME  VARCHAR(100) NOT NULL,
    PRICE_H  FLOAT,
    RANGE_H INTEGER DEFAULT 1,
    BEACH_NAME VARCHAR(100) NOT NULL,
    ID_L INTEGER,
    FOREIGN KEY (ID_L) REFERENCES Location(ID_L) ON DELETE CASCADE,
    PRIMARY KEY(H_ID,H_NAME)
  );
  
CREATE TABLE Description
  ( 
   T_ID INTEGER NOT NULL AUTO_INCREMENT,
   T_NAME VARCHAR(100) NOT NULL,
   FOREIGN KEY (T_NAME) REFERENCES TouristicSite(S_NAME) ON DELETE CASCADE,
   PRIMARY KEY(T_ID)
  );
